# Generated by Django 3.2.25 on 2025-08-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
