# Generated by Django 3.2.25 on 2025-08-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block_number',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
