# Generated by Django 3.2.25 on 2025-08-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
