# Generated by Django 3.2.25 on 2025-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_room_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
