# Generated by Django 3.2.25 on 2025-08-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='fees_student_49c91f_idx',
        ),
        migrations.AlterModelTable(
            name='fee',
            table=None,
        ),
    ]
