# Generated by Django 3.2.25 on 2025-08-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250828_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
