# Generated by Django 3.2.25 on 2025-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
