# Generated by Django 3.2.25 on 2025-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
