# Generated by Django 3.2.25 on 2025-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20250828_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, choices=[('BCA', 'BCA - Bachelor of Computer Applications'), ('BSC_CS', 'B.Sc Computer Science'), ('BSC_IT', 'B.Sc Information Technology'), ('BTECH_CS', 'B.Tech Computer Science & Engineering'), ('BTECH_IT', 'B.Tech Information Technology'), ('BTECH_EC', 'B.Tech Electronics & Communication'), ('BTECH_EE', 'B.Tech Electrical Engineering'), ('BTECH_ME', 'B.Tech Mechanical Engineering'), ('BTECH_CE', 'B.Tech Civil Engineering'), ('BTECH_AE', 'B.Tech Aeronautical Engineering'), ('MCA', 'MCA - Master of Computer Applications'), ('MSC_CS', 'M.Sc Computer Science'), ('MTECH_CS', 'M.Tech Computer Science & Engineering'), ('MTECH_IT', 'M.Tech Information Technology'), ('MTECH_EC', 'M.Tech Electronics & Communication'), ('MTECH_ME', 'M.Tech Mechanical Engineering'), ('MTECH_CE', 'M.Tech Civil Engineering'), ('MBA', 'MBA - Master of Business Administration'), ('DIP_CS', 'Diploma in Computer Science'), ('DIP_CE', 'Diploma in Civil Engineering'), ('DIP_ME', 'Diploma in Mechanical Engineering'), ('DIP_EE', 'Diploma in Electrical Engineering')], max_length=50, null=True),
        ),
    ]
