# Generated by Django 3.2.25 on 2025-08-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='transaction_id',
        ),
    ]
