# Generated by Django 5.2.5 on 2025-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20250829_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Unpaid', 'unpaid'), ('Pending', 'pending')], default='Unpaid', max_length=8),
        ),
    ]
