# Generated by Django 3.2.25 on 2025-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
