# Generated by Django 3.2.25 on 2025-08-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20250828_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_pic',
            field=models.FileField(blank=True, null=True, upload_to='meal_pic/'),
        ),
    ]
