# Generated by Django 3.2.25 on 2025-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_meal_meal_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('blocked', 'Blocked')], default='student', max_length=10),
        ),
    ]
