# Generated by Django 3.2.25 on 2025-08-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_alter_login_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
    ]
