# Generated by Django 5.2.5 on 2025-09-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_remove_notification_target'),
        ('room', '0007_alter_room_created_at'),
        ('student', '0009_alter_fee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(choices=[('room', 'Room'), ('maintenance', 'Maintenance'), ('billing', 'Billing'), ('mess', 'Mess / Food'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaint_attachments/')),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='room.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
